### ISSUE TITLE
encrypt consumer key and consumer secret key of twitter

### ISSUE THREAD

**Issue by ralian123** [fmcorey/sparrow#1]
I dont know how to encrypt consumer key and consumer secret key of twitter. it just give me invalid key id .would you please guide me ?

**Comment by fernando-mc** [comment]
Hi @ralian123 You can do this with the AWS CLI - https://docs.aws.amazon.com/cli/latest/reference/kms/encrypt.html

Or with an AWS SDK like the one for Python (boto3) - 
http://boto3.readthedocs.io/en/latest/reference/services/kms.html#KMS.Client.encrypt

When doing this you'll need to make sure you have a KMS key already created. You can do this in the AWS console or via the CLI - https://docs.aws.amazon.com/cli/latest/reference/kms/create-key.html

**Comment by ralian123** [comment]
so in IAM->Encryption keys->Create Key it asked for alias and description. where exactly you tie your twitter api keys? do I need to put the consumer key in alias?

**Comment by ralian123** [comment]
that is the part I can not get it where should I exactly put twitter keys?

**Comment by ralian123** [comment]
ok I got it I guess. I though in a key we need to put the key Id too. However, in Encryption keys we just create the key and the in aws cli we pass the value to it . thank you so much

**Comment by fernando-mc** [comment]
@ralian123 Glad you got it all figured out!

**Comment by velsarav** [comment]
Just added more info for twitter API encryption, 
encrypt.encrypt('consumer_key key value', 'alias/woofGarden')
encrypt.encrypt('consumer_secret key value', 'alias/woofGarden')
encrypt.encrypt('access_token_key key value', 'alias/woofGarden')
encrypt.encrypt('access_token_secret key value', 'alias/woofGarden')
Thanks @fernando-mc
